[package]
name = "rusty_web"
version = "0.1.0"
authors = ["aaron"]

[dependencies]
simple_logger = "0.4.0"
log = "0.3.8"

[dependencies.iron]
version = "0.5.1"

[dependencies.logger]
git = "https://github.com/iron/logger.git"
